# Generated by Django 5.0.7 on 2024-08-04 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingstargets',
            options={'verbose_name_plural': 'Savings Targets'},
        ),
    ]
